[package]
name = "renders"
version = "0.1.0"
edition = "2024"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
suboptimal-flops = "allow"
enum_glob_use = "deny"
pedantic = { level = "deny",  priority = -1 }
nursery = { level = "deny",  priority = -1 }
unwrap_used = "deny"

[dependencies]
